swagger.json

update swagger json

---

core/storage/boltStorage.go
core/storage/boltStorageHelpers.go
core/storage/boltStorage_test.go
core/storage/mongoStorage.go
core/storage/mongoStorage_test.go
core/storage/storage_test.go

Signed-off-by: Antonii Sirotsinskyi <asiro@softserveinc.com>

Issue 48 - ACL cleanup for Delete Org API

---

core/base/http.go

Issue 2249 - Allow UDS run as non-root user

---

core/base/apiServer.go

Issue 61 - Strict-Transport-Security Header Not Set

---

common/common.go
core/base/apiModule.go
core/base/apiModule_test.go
core/storage/boltStorage.go
core/storage/cache.go
core/storage/inMemoryStorage.go
core/storage/mongoStorage.go
core/storage/storage.go
swagger.json

Issue2485 - PR

---

core/communications/httpCommunication.go

Signed-off-by: Antonii Sirotsinskyi <asiro@softserveinc.com>

Issue 67 - Close response body for non-nil body

---

.gitignore
common/common.go
core/base/apiModule.go
core/base/apiModule_test.go
core/base/base.go
core/communications/httpCommunication.go
core/dataURI/dataURI.go
core/dataVerifier/dataVerifier.go
core/dataVerifier/dataVerifier_test.go
core/storage/boltStorage.go
core/storage/mongoStorage.go
runCoverage.sh

Issue 63 - Add data verification in Sync Service SPIs

---

common/common.go
core/base/apiModule.go
core/base/apiServer.go
core/communications/communicator.go
core/communications/httpCommunication.go
core/leader/leader.go
core/storage/mongoStorage.go

hzn mms object publish should support chunk uploading

---

core/communications/httpCommunication.go

Signed-off-by: Ben Courliss <bencourliss@ibm.com>

Issue 2985 - Updated to use 32 bit max int

---

common/common.go
core/base/apiServer.go
core/base/apiServer_test.go
core/storage/boltStorage.go
core/storage/mongoStorageHelpers.go
swagger.json

Issue 100 - CSS API to retrieve all object types under a given org

---

common/config.go

Update LeadershipTimout from 30s to 45s

---

core/base/apiModule.go
core/base/apiServer.go
core/base/apiServer_test.go

Issue 103 - CSS get data API should support chunk downloading

---

core/base/apiServer.go

Issue 103 (part2) - CSS get data API should support chunk downloading

---

common/common.go
core/base/apiModule.go
core/base/apiServer.go
core/base/objectVerifyQueue.go
core/dataVerifier/dataVerifier.go
core/storage/mongoStorage.go
core/storage/storage.go
core/storage/storage_test.go

Issue 108 - CSS avoid leader

---

core/storage/mongoStorage.go

Issue 110 - CSS delete temp data

---

core/storage/mongoStorage.go

Issue 112 - Fix change for issue 110

---

common/common.go
core/base/apiServer.go
core/base/apiServer_test.go
core/security/authentication.go
core/security/dummyAuthenticate.go
core/security/security.go
core/security/testAuthenticate.go

Issue 114 - Add ACL for manifest files

---

core/communications/communicator.go

Issue_118 Add 408 as retryable

---

core/storage/mongoStorage.go

Issue_121 Avoid OOM on model upload

---

core/base/base.go

Signed-off-by: John Walicki <johnwalicki@gmail.com>
Fixes : #133 
I corrected the spelling of `initialized` on three Info messages.

Issue 133: Fix misspellings of initialized

---

core/dataURI/dataURI.go

This PR improves the security of the DeleteStoredData function by properly sanitizing file path before deletion. It addresses a file manipulation vulnerability (CWE-73) flagged by security scans, preventing potential path traversal attacks.
File Manipulation vulnerability occurs when an application allows user input to control or influence paths or file names that are used in file system operations. This could allow an attacker to access or modify system files or other files that are critical to the application. For example, an application may give an attacker the ability to overwrite a specified file or run with a configuration controlled by the attacker
[166](https://github.com/open-horizon/edge-sync-service/issues/166)
[IEAM-1538](https://jsw.ibm.com/browse/IEAM-1538)

Fix file manipulation vulnerability

---

core/dataURI/dataURI.go

Issue open-horizon#166 - Fix CWE-73: File Manipulation

---

core/base/apiServer.go
swagger.json

Fixed some errors in swagger documentaion

Fix swagger json
